export const RIVER = { z0: 22, z1: 24, x0: -36, x1: 36 };

export const BRIDGE = {
  span: [22, 23, 24],
  mouth: [-1, 0, 1],
  plankCost: { madeira: 5, pedra: 3, blocos: 2 },
  gateSouthZ: 21,
  gateNorthZ: 25,
};

export const MATERIALS = [
  { id: 'madeira', name: 'Madeira', icon: '🪵', c: '#6B4226' },
  { id: 'pedra', name: 'Pedra', icon: '🪨', c: '#9A9A9A' },
  { id: 'blocos', name: 'Blocos', icon: '🧱', c: '#B3512A' },
];

export const START_MATERIALS = { madeira: 5, pedra: 3, blocos: 2 };

export const CHALLENGE_REWARD_MATERIALS = { madeira: 2, pedra: 1, blocos: 1 };

export const SERIE_LEVEL = {
  '1º EF': '6_ano_fund', '2º EF': '6_ano_fund', '3º EF': '6_ano_fund', '4º EF': '6_ano_fund', '5º EF': '6_ano_fund',
  '6º EF': '6_ano_fund', '7º EF': '7_ano_fund', '8º EF': '8_ano_fund', '9º EF': '9_ano_fund',
  '1ª EM': '1_medio', '2ª EM': '2_medio', '3ª EM': '3_medio',
};

export const poolForLevel = (pool, level, min = 3) => {
  if (!level) return pool;
  const fit = pool.filter((q) => (q.level || SERIE_LEVEL[q.serie]) === level);
  return fit.length >= min ? fit : pool;
};

export const QUESTIONS = [
  { serie: '5º EF', cat: 'fracoes', q: 'Quanto é 1/2 + 1/4?', opts: ['2/6', '3/4', '1/8', '2/4'], a: 1 },
  { serie: '5º EF', cat: 'fracoes', q: 'Qual fração equivale a 0,5?', opts: ['1/3', '5/2', '1/2', '2/5'], a: 2 },
  { serie: '6º EF', cat: 'fracoes', q: 'Simplifique 8/12:', opts: ['4/6', '2/3', '3/4', '1/2'], a: 1 },
  { serie: '6º EF', cat: 'fracoes', q: 'Quem é maior: 3/5 ou 7/10?', opts: ['3/5', '7/10', 'Iguais', 'Não dá pra comparar'], a: 1 },
  { serie: '7º EF', cat: 'porcentagem', q: 'Quanto é 50% de 200?', opts: ['50', '150', '100', '25'], a: 2 },
  { serie: '8º EF', cat: 'porcentagem', q: 'Um desconto de 10% em R$80 fica:', opts: ['R$72', 'R$70', 'R$8', 'R$71'], a: 0 },
  { serie: '6º EF', cat: 'porcentagem', q: '25% é o mesmo que:', opts: ['1/2', '1/4', '1/5', '1/3'], a: 1 },
  { serie: '7º EF', cat: 'porcentagem', q: '15% de 300:', opts: ['45', '30', '15', '60'], a: 0 },
  { serie: '2º EF', cat: 'geometria', q: 'Quantos lados tem um hexágono?', opts: ['5', '8', '6', '7'], a: 2 },
  { serie: '7º EF', cat: 'geometria', q: 'A soma dos ângulos internos de um triângulo é:', opts: ['180°', '90°', '360°', '270°'], a: 0 },
  { serie: '5º EF', cat: 'geometria', q: 'Área de um quadrado de lado 4:', opts: ['8', '12', '16', '20'], a: 2 },
  { serie: '8º EF', cat: 'geometria', q: 'Quantos vértices tem um cubo?', opts: ['6', '8', '10', '12'], a: 1 },
  { serie: '6º EF', cat: 'final', q: 'Se 3x = 27, quanto vale x?', opts: ['7', '9', '8', '6'], a: 1 },
  { serie: '4º EF', cat: 'final', q: 'Quanto é 12 × 8?', opts: ['96', '84', '108', '90'], a: 0 },
  { serie: '5º EF', cat: 'final', q: 'Uma pizza tem 8 fatias. Você come 3. Que fração sobrou?', opts: ['3/8', '5/8', '5/3', '2/8'], a: 1 },
  { serie: '2º EF', cat: 'fracoes', q: 'Uma pizza foi dividida em 4 pedaços iguais. Você comeu 1 pedaço. Que fração da pizza você comeu?', opts: ['1/2', '1/4', '2/4', '1/3'], a: 1 },
  { serie: '2º EF', cat: 'fracoes', q: 'A metade de um número é 6. Qual é o número?', opts: ['3', '12', '6', '9'], a: 1 },
  { serie: '3º EF', cat: 'fracoes', q: 'Que fração representa 2 partes coloridas de um total de 5?', opts: ['2/5', '5/2', '3/5', '2/3'], a: 0 },
  { serie: '5º EF', cat: 'fracoes', q: 'Qual fração é maior que um inteiro?', opts: ['3/4', '4/5', '7/3', '5/5'], a: 2 },
  { serie: '6º EF', cat: 'fracoes', q: '2/3 de 12 é igual a:', opts: ['4', '6', '8', '9'], a: 2 },
  { serie: '7º EF', cat: 'fracoes', q: 'Quanto é 3/4 + 1/2?', opts: ['4/6', '1/4', '5/4', '5/2'], a: 2 },
  { serie: '7º EF', cat: 'fracoes', q: 'Multiplique 2/3 × 3/4:', opts: ['6/7', '1/2', '5/12', '9/12'], a: 1 },
  { serie: '9º EF', cat: 'fracoes', q: 'Qual é o valor de 1/2 ÷ 3/4?', opts: ['3/2', '2/3', '1/6', '3/8'], a: 1 },
  { serie: '9º EF', cat: 'fracoes', q: 'Qual fração é equivalente a 0,75?', opts: ['3/4', '7/5', '3/5', '1/4'], a: 0 },
  { serie: '6º EF', cat: 'porcentagem', q: 'Quanto é 10% de 50?', opts: ['5', '10', '15', '50'], a: 0 },
  { serie: '7º EF', cat: 'porcentagem', q: 'Em uma escola de 500 alunos, 40% são meninas. Quantas meninas há?', opts: ['150', '200', '250', '300'], a: 1 },
  { serie: '8º EF', cat: 'porcentagem', q: 'Um produto custa R$120 e teve um aumento de 5%. Qual é o novo preço?', opts: ['R$125', 'R$126', 'R$130', 'R$124'], a: 1 },
  { serie: '8º EF', cat: 'porcentagem', q: 'Quanto é 75% de 40?', opts: ['20', '30', '25', '35'], a: 1 },
  { serie: '9º EF', cat: 'porcentagem', q: 'Um valor caiu de R$80 para R$60. Qual foi o percentual de desconto?', opts: ['20%', '25%', '30%', '15%'], a: 1 },
  { serie: '9º EF', cat: 'porcentagem', q: 'Em uma prova de 50 questões, Pedro acertou 42. Qual foi o percentual de acertos?', opts: ['80%', '84%', '86%', '90%'], a: 1 },
  { serie: '3ª EM', cat: 'porcentagem', q: 'Qual é o montante de R$1000 aplicado a 10% ao ano em juros simples por 2 anos?', opts: ['R$1100', 'R$1200', 'R$1210', 'R$1000'], a: 1 },
  { serie: '3ª EM', cat: 'porcentagem', q: 'Um aumento de 20% seguido de um desconto de 20% sobre R$100 resulta em:', opts: ['R$100', 'R$96', 'R$104', 'R$90'], a: 1 },
  { serie: '1º EF', cat: 'geometria', q: 'Quantos lados tem um triângulo?', opts: ['2', '3', '4', '5'], a: 1 },
  { serie: '2º EF', cat: 'geometria', q: 'A figura que tem 4 lados iguais é o:', opts: ['quadrado', 'triângulo', 'círculo', 'retângulo'], a: 0 },
  { serie: '5º EF', cat: 'geometria', q: 'O perímetro de um retângulo de 6 cm por 4 cm é:', opts: ['10 cm', '20 cm', '24 cm', '12 cm'], a: 1 },
  { serie: '6º EF', cat: 'geometria', q: 'A área de um retângulo de base 8 e altura 3 é:', opts: ['24', '11', '22', '12'], a: 0 },
  { serie: '7º EF', cat: 'geometria', q: 'A soma dos ângulos internos de um quadrilátero é:', opts: ['180°', '360°', '270°', '90°'], a: 1 },
  { serie: '8º EF', cat: 'geometria', q: 'Um triângulo que tem dois lados iguais é chamado de:', opts: ['escaleno', 'equilátero', 'isósceles', 'obtuso'], a: 2 },
  { serie: '8º EF', cat: 'geometria', q: 'O volume de um cubo com aresta 3 é:', opts: ['9', '18', '27', '12'], a: 2 },
  { serie: '9º EF', cat: 'geometria', q: 'Num triângulo retângulo com catetos 3 e 4, a hipotenusa mede:', opts: ['5', '6', '7', '8'], a: 0 },
  { serie: '5º EF', cat: 'final', q: 'Ana tinha 25 figurinhas, ganhou 18 e perdeu 7. Com quantas ficou?', opts: ['33', '36', '43', '50'], a: 1 },
  { serie: '5º EF', cat: 'final', q: 'João comprou 3 lápis por R$4 cada e pagou com R$20. Quanto recebeu de troco?', opts: ['R$8', 'R$12', 'R$6', 'R$4'], a: 0 },
  { serie: '6º EF', cat: 'final', q: 'Qual é o resultado de 2 × 3 + 4?', opts: ['10', '14', '12', '18'], a: 0 },
  { serie: '7º EF', cat: 'final', q: 'Qual destes números NÃO é divisível por 3?', opts: ['12', '27', '35', '33'], a: 2 },
  { serie: '7º EF', cat: 'final', q: 'A raiz quadrada de 81 é:', opts: ['7', '8', '9', '11'], a: 2 },
  { serie: '8º EF', cat: 'final', q: 'O valor de -3 + 8 é:', opts: ['5', '-5', '11', '-11'], a: 0 },
  { serie: '8º EF', cat: 'final', q: 'Quanto é 2³?', opts: ['6', '8', '9', '23'], a: 1 },
  { serie: '9º EF', cat: 'final', q: 'Resolva 2(x + 3) = 14:', opts: ['x = 4', 'x = 5', 'x = 6', 'x = 7'], a: 0 },
  { serie: '3ª EM', cat: 'final', q: 'Se f(x) = 2x - 1, qual é o valor de f(5)?', opts: ['9', '10', '11', '8'], a: 0 },
  { serie: '2º EF', cat: 'numeros', q: 'Qual número vem depois de 99?', opts: ['98', '100', '101', '90'], a: 1 },
  { serie: '3º EF', cat: 'numeros', q: '5 dezenas mais 3 unidades formam o número:', opts: ['53', '35', '503', '85'], a: 0 },
  { serie: '4º EF', cat: 'numeros', q: 'Quanto é 2 × 45?', opts: ['80', '90', '95', '100'], a: 1 },
  { serie: '5º EF', cat: 'numeros', q: 'Quanto é 384 + 219?', opts: ['503', '603', '703', '583'], a: 1 },
  { serie: '5º EF', cat: 'numeros', q: 'Arredondando 438 para a dezena mais próxima, obtemos:', opts: ['400', '440', '430', '500'], a: 1 },
  { serie: '6º EF', cat: 'numeros', q: 'O MMC de 4 e 6 é:', opts: ['12', '24', '18', '36'], a: 0 },
  { serie: '7º EF', cat: 'numeros', q: 'O MDC de 12 e 18 é:', opts: ['6', '3', '9', '36'], a: 0 },
  { serie: '9º EF', cat: 'numeros', q: 'Quantos divisores tem o número 12?', opts: ['4', '5', '6', '8'], a: 2 },
  { serie: '3ª EM', cat: 'numeros', q: '1,5 × 10³ é igual a:', opts: ['1500', '150', '15000', '105'], a: 0 },
  { serie: '2º EF', cat: 'numeros', q: 'Meia dúzia são quantas unidades?', opts: ['12', '6', '10', '5'], a: 1 },
  { serie: '4º EF', cat: 'algebra', q: 'Complete a sequência: 2, 4, 6, 8, ___', opts: ['9', '10', '11', '12'], a: 1 },
  { serie: '5º EF', cat: 'algebra', q: 'Se a = b + 3 e b = 7, quanto vale a?', opts: ['10', '4', '21', '11'], a: 0 },
  { serie: '6º EF', cat: 'algebra', q: 'Qual é o valor de x em x + 7 = 15?', opts: ['7', '8', '22', '6'], a: 1 },
  { serie: '7º EF', cat: 'algebra', q: 'Se 4x = 36, quanto vale x?', opts: ['6', '8', '9', '12'], a: 2 },
  { serie: '7º EF', cat: 'algebra', q: 'Se 2x - 5 = 9, então x vale:', opts: ['7', '6', '5', '8'], a: 0 },
  { serie: '8º EF', cat: 'algebra', q: 'Simplifique 6a + 3a:', opts: ['9a', '6a', '3a', '9'], a: 0 },
  { serie: '9º EF', cat: 'algebra', q: 'As raízes da equação x² - 9 = 0 são:', opts: ['3 e -3', '9 e -9', '0 e 9', '3 e 0'], a: 0 },
  { serie: '3ª EM', cat: 'algebra', q: 'A função f(x) = x² + 1, para x = 2, vale:', opts: ['5', '4', '6', '3'], a: 0 },
  { serie: '2º EF', cat: 'medidas', q: 'Quantas horas tem um dia?', opts: ['24', '12', '6', '60'], a: 0 },
  { serie: '3º EF', cat: 'medidas', q: '1 metro equivale a:', opts: ['100 cm', '10 cm', '1000 cm', '10 mm'], a: 0 },
  { serie: '4º EF', cat: 'medidas', q: 'Uma semana tem quantos dias?', opts: ['5', '7', '10', '12'], a: 1 },
  { serie: '5º EF', cat: 'medidas', q: '1 litro equivale a:', opts: ['1000 ml', '100 ml', '10 ml', '500 ml'], a: 0 },
  { serie: '5º EF', cat: 'medidas', q: 'Meio quilo corresponde a:', opts: ['50 g', '500 g', '1000 g', '250 g'], a: 1 },
  { serie: '6º EF', cat: 'medidas', q: '1 hora e 30 minutos correspondem a:', opts: ['90 min', '120 min', '60 min', '150 min'], a: 0 },
  { serie: '8º EF', cat: 'medidas', q: 'A área de um quadrado de lado 12 cm é:', opts: ['144 cm²', '48 cm²', '24 cm²', '121 cm²'], a: 0 },
  { serie: '9º EF', cat: 'medidas', q: '2,5 km equivalem a:', opts: ['250 m', '2500 m', '25 000 m', '25 m'], a: 1 },
  { serie: '3ª EM', cat: 'medidas', q: 'Um terreno retangular de 30 m por 20 m tem área de:', opts: ['600 m²', '100 m²', '50 m²', '6000 m²'], a: 0 },
  { serie: '3º EF', cat: 'medidas', q: 'Um real e meio equivale a:', opts: ['R$1,05', 'R$1,50', 'R$1,15', 'R$0,50'], a: 1 },
  { serie: '5º EF', cat: 'probabilidade', q: 'Ao lançar uma moeda, qual é a probabilidade de sair cara?', opts: ['1/2', '1/4', '1', '2/3'], a: 0 },
  { serie: '5º EF', cat: 'probabilidade', q: 'Em um dado de 6 faces, qual é a chance de sair o número 3?', opts: ['1/6', '1/3', '1/2', '3/6'], a: 0 },
  { serie: '7º EF', cat: 'probabilidade', q: 'Em uma sacola com 3 bolas vermelhas e 2 azuis, a probabilidade de tirar uma vermelha é:', opts: ['3/5', '2/5', '3/2', '1/5'], a: 0 },
  { serie: '7º EF', cat: 'probabilidade', q: 'Um evento impossível tem probabilidade igual a:', opts: ['0', '1', '1/2', '10%'], a: 0 },
  { serie: '8º EF', cat: 'probabilidade', q: 'Numa turma de 25 alunos, 10 usam óculos. A probabilidade de sortear um aluno que usa óculos é:', opts: ['2/5', '1/5', '1/2', '1/25'], a: 0 },
  { serie: '9º EF', cat: 'probabilidade', q: 'A média das notas 6, 7 e 8 é:', opts: ['7', '6,5', '8', '7,5'], a: 0 },
  { serie: '9º EF', cat: 'probabilidade', q: 'A mediana dos números 2, 5, 9, 11 e 13 é:', opts: ['9', '7', '11', '8'], a: 0 },
  { serie: '3ª EM', cat: 'probabilidade', q: 'Lançando dois dados, quantos resultados possíveis existem no total?', opts: ['36', '12', '24', '6'], a: 0 },
  { serie: '6º EF', cat: 'fracoes', q: 'Qual fração está na forma irredutível?', opts: ['2/4', '3/6', '7/8', '10/15'], a: 2 },
  { serie: '6º EF', cat: 'fracoes', q: 'Entre 1/2 e 3/4, qual é a maior?', opts: ['1/2', '3/4', 'São iguais', 'Não dá para comparar'], a: 1 },
  { serie: '7º EF', cat: 'fracoes', q: 'Quanto é 2/5 + 3/10?', opts: ['5/10', '7/10', '5/15', '2/5'], a: 1 },
  { serie: '7º EF', cat: 'fracoes', q: 'Quanto é 5/6 - 1/3?', opts: ['1/2', '4/3', '2/3', '1/6'], a: 0 },
  { serie: '8º EF', cat: 'fracoes', q: 'Qual é o resultado de 3/4 × 4/3?', opts: ['1', '3/4', '4/3', '9/16'], a: 0 },
  { serie: '8º EF', cat: 'fracoes', q: 'Quanto é 1/2 ÷ 1/2?', opts: ['1', '1/4', '0', '2'], a: 0 },
  { serie: '9º EF', cat: 'fracoes', q: 'Qual número decimal representa 3/8?', opts: ['0,375', '0,38', '0,35', '3,8'], a: 0 },
  { serie: '1ª EM', cat: 'fracoes', q: 'Qual é a fração geratriz de 0,333...?', opts: ['1/3', '3/10', '1/4', '3/3'], a: 0 },
  { serie: '2ª EM', cat: 'fracoes', q: 'Simplificando a²b / ab³, obtemos:', opts: ['a/b²', 'a²b', 'b/a', '1/ab'], a: 0 },
  { serie: '3ª EM', cat: 'fracoes', q: 'Quanto é 2/3 + 1/6?', opts: ['5/6', '3/9', '1/2', '4/9'], a: 0 },
  { serie: '6º EF', cat: 'porcentagem', q: 'Quanto é 30% de 90?', opts: ['27', '30', '40', '33'], a: 0 },
  { serie: '7º EF', cat: 'porcentagem', q: 'Um brinquedo de R$50 ganhou 20% de desconto. Qual o valor do desconto?', opts: ['R$10', 'R$20', 'R$5', 'R$15'], a: 0 },
  { serie: '8º EF', cat: 'porcentagem', q: 'Quanto é 5% de 400?', opts: ['20', '25', '30', '40'], a: 0 },
  { serie: '9º EF', cat: 'porcentagem', q: 'Se já se passaram 15 dos 30 dias do mês, que percentual passou?', opts: ['50%', '25%', '75%', '40%'], a: 0 },
  { serie: '1ª EM', cat: 'porcentagem', q: 'Um aumento de 10% seguido de desconto de 10% sobre R$200 resulta em:', opts: ['R$198', 'R$200', 'R$202', 'R$196'], a: 0 },
  { serie: '2ª EM', cat: 'porcentagem', q: 'Um capital de R$500 rendeu R$60 em juros simples a 3% ao mês. Por quantos meses?', opts: ['4', '3', '5', '6'], a: 0 },
  { serie: '3ª EM', cat: 'porcentagem', q: 'Qual percentual representa 3/5?', opts: ['60%', '35%', '53%', '66%'], a: 0 },
  { serie: '6º EF', cat: 'geometria', q: 'O perímetro de um quadrado de lado 7 cm é:', opts: ['28 cm', '14 cm', '49 cm', '21 cm'], a: 0 },
  { serie: '6º EF', cat: 'geometria', q: 'Um ângulo reto mede:', opts: ['90°', '45°', '180°', '360°'], a: 0 },
  { serie: '7º EF', cat: 'geometria', q: 'Um ângulo de 120° é classificado como:', opts: ['obtuso', 'agudo', 'reto', 'raso'], a: 0 },
  { serie: '7º EF', cat: 'geometria', q: 'Dois ângulos complementares somam:', opts: ['90°', '180°', '120°', '60°'], a: 0 },
  { serie: '8º EF', cat: 'geometria', q: 'A soma dos ângulos internos de um pentágono é:', opts: ['540°', '360°', '180°', '720°'], a: 0 },
  { serie: '8º EF', cat: 'geometria', q: 'Duas retas que nunca se encontram são:', opts: ['paralelas', 'perpendiculares', 'concorrentes', 'coincidentes'], a: 0 },
  { serie: '9º EF', cat: 'geometria', q: 'A área de um círculo de raio 10 (com π = 3,14) é aproximadamente:', opts: ['314', '100', '628', '31,4'], a: 0 },
  { serie: '9º EF', cat: 'geometria', q: 'O teorema de Pitágoras relaciona:', opts: ['os catetos e a hipotenusa', 'lados e ângulos', 'raio e diâmetro', 'vértices e arestas'], a: 0 },
  { serie: '1ª EM', cat: 'geometria', q: 'O seno de 30° vale:', opts: ['1/2', '√3/2', '1', '√2/2'], a: 0 },
  { serie: '2ª EM', cat: 'geometria', q: 'O volume de um cilindro de raio 2 e altura 5 (com π = 3) é:', opts: ['60', '20', '30', '15'], a: 0 },
  { serie: '3ª EM', cat: 'geometria', q: 'A distância entre os pontos (0,0) e (3,4) é:', opts: ['5', '7', '1', '25'], a: 0 },
  { serie: '6º EF', cat: 'final', q: 'Quanto é 4 × 3 + 2?', opts: ['14', '20', '24', '18'], a: 0 },
  { serie: '7º EF', cat: 'final', q: 'O valor de |−7| é:', opts: ['7', '−7', '0', '14'], a: 0 },
  { serie: '7º EF', cat: 'final', q: 'Quanto é 0,5 × 0,4?', opts: ['0,20', '0,9', '2,0', '0,09'], a: 0 },
  { serie: '8º EF', cat: 'final', q: 'Quanto é 2⁴ + 2²?', opts: ['20', '24', '16', '64'], a: 0 },
  { serie: '8º EF', cat: 'final', q: 'Se um triângulo isósceles tem o ângulo do vértice medindo 80°, cada ângulo da base mede:', opts: ['50°', '80°', '100°', '40°'], a: 0 },
  { serie: '9º EF', cat: 'final', q: 'O valor de x em 3x - 6 = 9 é:', opts: ['5', '3', '6', '9'], a: 0 },
  { serie: '1ª EM', cat: 'final', q: 'As raízes de f(x) = x² - 4 são:', opts: ['2 e −2', '4 e −4', '0 e 4', '2 e 4'], a: 0 },
  { serie: '2ª EM', cat: 'final', q: 'O determinante da matriz [[2,3],[1,4]] é:', opts: ['5', '10', '8', '11'], a: 0 },
  { serie: '3ª EM', cat: 'final', q: 'A probabilidade de sair um número par em um dado é:', opts: ['1/2', '1/3', '1/6', '2/3'], a: 0 },
  { serie: '6º EF', cat: 'numeros', q: 'O quociente de 0,6 ÷ 0,2 é:', opts: ['3', '30', '0,3', '12'], a: 0 },
  { serie: '6º EF', cat: 'numeros', q: 'O MMC de 3 e 5 é:', opts: ['15', '8', '30', '10'], a: 0 },
  { serie: '7º EF', cat: 'numeros', q: 'O MDC de 8 e 12 é:', opts: ['4', '2', '6', '24'], a: 0 },
  { serie: '7º EF', cat: 'numeros', q: 'O valor de (−2)³ é:', opts: ['−8', '8', '−6', '6'], a: 0 },
  { serie: '8º EF', cat: 'numeros', q: 'Quanto é 2,4 × 10²?', opts: ['240', '24', '2400', '204'], a: 0 },
  { serie: '8º EF', cat: 'numeros', q: 'A raiz quadrada de 225 é:', opts: ['15', '25', '45', '35'], a: 0 },
  { serie: '9º EF', cat: 'numeros', q: 'O número 81 em notação científica é:', opts: ['8,1 × 10¹', '8,1 × 10²', '81 × 10', '0,81 × 10²'], a: 0 },
  { serie: '1ª EM', cat: 'numeros', q: 'Quantos elementos tem o conjunto dos divisores de 18?', opts: ['6', '4', '8', '9'], a: 0 },
  { serie: '2ª EM', cat: 'numeros', q: 'O logaritmo log10(1000) é igual a:', opts: ['3', '10', '100', '1'], a: 0 },
  { serie: '3ª EM', cat: 'numeros', q: 'Quanto é 3! (fatorial de 3)?', opts: ['6', '9', '24', '12'], a: 0 },
  { serie: '6º EF', cat: 'algebra', q: 'O perímetro de um retângulo x por 2x é:', opts: ['6x', '3x', '4x', '8x'], a: 0 },
  { serie: '6º EF', cat: 'algebra', q: 'Na expressão 5y, o coeficiente é:', opts: ['5', 'y', '5y', '1'], a: 0 },
  { serie: '7º EF', cat: 'algebra', q: 'Quanto é 3x + 2x - x?', opts: ['4x', '5x', '6x', '3x'], a: 0 },
  { serie: '7º EF', cat: 'algebra', q: 'Se x = 2, quanto vale x² + 3?', opts: ['7', '5', '9', '8'], a: 0 },
  { serie: '8º EF', cat: 'algebra', q: 'A soma de (2x + 1) e (3x - 4) é:', opts: ['5x − 3', '5x + 5', '6x − 4', '−x − 3'], a: 0 },
  { serie: '8º EF', cat: 'algebra', q: 'Resolva 3(2x - 1) = 9:', opts: ['x = 2', 'x = 1', 'x = 3', 'x = 4'], a: 0 },
  { serie: '9º EF', cat: 'algebra', q: 'As soluções de x² - 5x + 6 = 0 são:', opts: ['2 e 3', '1 e 6', '−2 e −3', '3 e 6'], a: 0 },
  { serie: '9º EF', cat: 'algebra', q: 'A função afim que passa por (0,3) e (1,5) é:', opts: ['f(x) = 2x + 3', 'f(x) = 3x + 2', 'f(x) = 5x', 'f(x) = 2x − 3'], a: 0 },
  { serie: '1ª EM', cat: 'algebra', q: 'O eixo de simetria da parábola f(x) = x² - 4x + 1 é x =', opts: ['2', '−2', '4', '1'], a: 0 },
  { serie: '2ª EM', cat: 'algebra', q: 'A progressão geométrica 2, 6, 18,... tem razão:', opts: ['3', '6', '2', '9'], a: 0 },
  { serie: '3ª EM', cat: 'algebra', q: 'O limite de 1/x quando x tende ao infinito é:', opts: ['0', '1', '∞', '−1'], a: 0 },
  { serie: '6º EF', cat: 'medidas', q: 'Meia hora corresponde a:', opts: ['30 min', '60 min', '15 min', '45 min'], a: 0 },
  { serie: '6º EF', cat: 'medidas', q: 'Uma piscina de 2 m × 4 m × 1,5 m tem volume de:', opts: ['12 m³', '8 m³', '6 m³', '10 m³'], a: 0 },
  { serie: '7º EF', cat: 'medidas', q: 'O perímetro de um terreno retangular de 12 m por 8 m é:', opts: ['40 m', '20 m', '96 m', '44 m'], a: 0 },
  { serie: '7º EF', cat: 'medidas', q: 'Um quilo e meio corresponde a:', opts: ['1500 g', '1050 g', '15 g', '150 g'], a: 0 },
  { serie: '8º EF', cat: 'medidas', q: 'Um carro percorreu 200 km em 4 h. A velocidade média foi de:', opts: ['50 km/h', '40 km/h', '60 km/h', '80 km/h'], a: 0 },
  { serie: '8º EF', cat: 'medidas', q: 'A temperatura normal do corpo humano é próxima de:', opts: ['36°C', '39°C', '33°C', '41°C'], a: 0 },
  { serie: '9º EF', cat: 'medidas', q: 'Um atleta percorre 300 m em 60 s. Sua velocidade média é:', opts: ['5 m/s', '3 m/s', '50 m/s', '0,2 m/s'], a: 0 },
  { serie: '1ª EM', cat: 'medidas', q: 'A distância de 1,5 km em metros é:', opts: ['1500 m', '150 m', '15 m', '15 000 m'], a: 0 },
  { serie: '2ª EM', cat: 'medidas', q: 'A área total de um cubo de aresta 3 é:', opts: ['54', '36', '27', '18'], a: 0 },
  { serie: '3ª EM', cat: 'medidas', q: '1 m³ equivale a:', opts: ['1000 litros', '100 litros', '10 litros', '10 000 litros'], a: 0 },
  { serie: '6º EF', cat: 'probabilidade', q: 'Retirando uma carta de um baralho de 52, a chance de sair um Ás é:', opts: ['4/52', '1/52', '13/52', '26/52'], a: 0 },
  { serie: '7º EF', cat: 'probabilidade', q: 'Em um sorteio de 1 a 20, a chance de um número ser múltiplo de 5 é:', opts: ['4/20', '1/20', '5/20', '10/20'], a: 0 },
  { serie: '8º EF', cat: 'probabilidade', q: 'A frequência absoluta do número 2 na sequência 2, 3, 5, 2, 2, 7 é:', opts: ['3', '2', '5', '1'], a: 0 },
  { serie: '8º EF', cat: 'probabilidade', q: 'A moda dos números 4, 7, 4, 9, 4, 2 é:', opts: ['4', '7', '9', '2'], a: 0 },
  { serie: '9º EF', cat: 'probabilidade', q: 'Lançando duas moedas, a probabilidade de duas caras é:', opts: ['1/4', '1/2', '1/3', '1/8'], a: 0 },
  { serie: '9º EF', cat: 'probabilidade', q: 'A média de 5, 10 e 15 é:', opts: ['10', '15', '20', '30'], a: 0 },
  { serie: '1ª EM', cat: 'probabilidade', q: 'Lançando um dado e uma moeda, quantos resultados possíveis existem?', opts: ['12', '8', '6', '36'], a: 0 },
  { serie: '2ª EM', cat: 'probabilidade', q: 'Em 30 alunos, 12 preferem música. A probabilidade de sortear um deles é:', opts: ['2/5', '1/5', '1/4', '3/5'], a: 0 },
  { serie: '3ª EM', cat: 'probabilidade', q: 'Se P(A) = 0,3 e P(B) = 0,5 com A e B independentes, então P(A ∩ B) é:', opts: ['0,15', '0,8', '0,2', '0,05'], a: 0 },
];

export const SUBJECT_QUESTIONS = {
  portugues: [
    { serie: '5º EF', q: 'Qual frase está no plural?', opts: ['O menino corre.', 'Os meninos correm.', 'A menina corre.', 'O menino corre rápido.'], a: 1 },
    { serie: '5º EF', q: 'Sinônimo de "feliz"?', opts: ['Triste', 'Radiante', 'Raivoso', 'Cansado'], a: 1 },
    { serie: '4º EF', q: 'Qual palavra é um substantivo?', opts: ['Correr', 'Bonito', 'Livro', 'Rapidamente'], a: 2 },
    { serie: '6º EF', q: 'O que é um parágrafo?', opts: ['Um ponto final', 'Uma ideia com começo, meio e fim', 'Uma pergunta', 'Um título'], a: 1 },
    { serie: '2º EF', q: 'Qual destas palavras começa com a letra B?', opts: ['Casa', 'Banana', 'Gato', 'Sol'], a: 1 },
    { serie: '3º EF', q: 'Qual frase está escrita corretamente?', opts: ['A casa está grande.', 'A caza esta grande.', 'A casa estam grande.', 'As casa está grande.'], a: 0 },
    { serie: '5º EF', q: 'O antônimo de "grande" é:', opts: ['imenso', 'pequeno', 'enorme', 'gigante'], a: 1 },
    { serie: '5º EF', q: 'Qual é o verbo da frase "Ela estudou muito"?', opts: ['Ela', 'estudou', 'muito', 'boa'], a: 1 },
    { serie: '6º EF', q: 'Na frase "O livro é interessante", o adjetivo é:', opts: ['livro', 'é', 'interessante', 'O'], a: 2 },
    { serie: '6º EF', q: 'Qual é o plural de "cidadão"?', opts: ['cidadãos', 'cidadões', 'cidadães', 'cidadans'], a: 0 },
    { serie: '7º EF', q: 'Na frase "Maria comprou o bolo", o sujeito é:', opts: ['Maria', 'comprou', 'bolo', 'o bolo'], a: 0 },
    { serie: '8º EF', q: 'A palavra "submarino" é formada por:', opts: ['prefixo sub + radical mar', 'radical sub + sufixo o', 'duas palavras separadas', 'apenas um radical'], a: 0 },
    { serie: '9º EF', q: 'Ana foi ao cinema, mas esqueceu o ingresso. A palavra mas expressa:', opts: ['oposição', 'causa', 'finalidade', 'tempo'], a: 0 },
    { serie: '9º EF', q: 'Na frase "O carro que comprei é vermelho", a palavra que é um:', opts: ['pronome relativo', 'artigo', 'advérbio', 'substantivo'], a: 0 },
    { serie: '3ª EM', q: 'Qual alternativa apresenta um período composto por coordenação?', opts: ['Estudei e passei na prova.', 'A aluna que estudou passou.', 'Passei porque estudei.', 'Estudando, passei.'], a: 0 },
    { serie: '3º EF', q: 'Qual é a finalidade principal de um convite?', opts: ['Convidar alguém para um evento', 'Informar notícias', 'Contar uma história', 'Explicar uma regra'], a: 0 },
    { serie: '6º EF', q: 'Qual das palavras é um advérbio de tempo?', opts: ['ontem', 'bonito', 'caderno', 'correndo'], a: 0 },
    { serie: '6º EF', q: 'O gênero textual crônica aborda principalmente:', opts: ['fatos e situações do cotidiano', 'descobertas científicas', 'contas matemáticas', 'textos de lei'], a: 0 },
    { serie: '7º EF', q: 'O ponto de exclamação serve para:', opts: ['exprimir emoção ou espanto', 'indicar uma pergunta', 'separar sujeito e verbo', 'terminar uma declaração neutra'], a: 0 },
    { serie: '7º EF', q: 'Em "Ele próprio resolveu o problema", o pronome próprio é:', opts: ['reflexivo', 'indefinido', 'possessivo', 'demonstrativo'], a: 0 },
    { serie: '8º EF', q: 'O discurso direto transmite:', opts: ['a fala exata do personagem', 'o resumo da fala', 'a opinião do autor', 'a narração indireta'], a: 0 },
    { serie: '8º EF', q: 'As aspas são usadas para:', opts: ['marcar citação ou fala de alguém', 'indicar pausa curta', 'marcar plural', 'unir palavras compostas'], a: 0 },
    { serie: '9º EF', q: 'Na oração reduzida "chegando em casa, ligou a TV", o trecho destacado equivale a:', opts: ['quando chegou em casa', 'chegar em casa', 'a casa chegou', 'chegou em casa'], a: 0 },
    { serie: '9º EF', q: 'Numa tirinha, a linguagem verbal e a não verbal:', opts: ['se combinam para construir o sentido', 'nunca se relacionam', 'só a verbal importa', 'disputam o mesmo espaço'], a: 0 },
    { serie: '9º EF', q: 'O tema de um texto é:', opts: ['a ideia central sobre o que se fala', 'a primeira frase', 'o título', 'a opinião do leitor'], a: 0 },
    { serie: '9º EF', q: 'Na frase "vende-se casas" há um problema de:', opts: ['concordância verbal', 'ortografia', 'pontuação', 'acentuação'], a: 0 },
    { serie: '1ª EM', q: 'O modo verbal que expressa ordem ou pedido é o:', opts: ['imperativo', 'indicativo', 'subjuntivo', 'infinitivo'], a: 0 },
    { serie: '1ª EM', q: 'O texto dissertativo-argumentativo tem como objetivo:', opts: ['defender um ponto de vista', 'contar uma história', 'descrever um lugar', 'explicar como fazer algo'], a: 0 },
    { serie: '2ª EM', q: 'Em "estudou bastante, portanto passou", a palavra portanto expressa:', opts: ['conclusão', 'oposição', 'condição', 'tempo'], a: 0 },
    { serie: '2ª EM', q: 'Assinale a frase correta:', opts: ['Havia muitos alunos na sala.', 'Haviam muitos alunos na sala.', 'Existia muitas pessoas.', 'Fazem três anos da reunião.'], a: 0 },
    { serie: '3ª EM', q: 'Na função conativa (apelativa) da linguagem, o emissor busca:', opts: ['convencer o receptor', 'expressar emoções', 'falar da própria linguagem', 'apenas informar'], a: 0 },
    { serie: '3ª EM', q: 'Intertextualidade é:', opts: ['o diálogo entre textos', 'texto sem parágrafos', 'cópia literal proibida', 'um texto muito curto'], a: 0 },
    { serie: '1ª EM', q: 'Na norma culta, a frase "a gente vamos" apresenta:', opts: ['erro de concordância verbal', 'uso correto', 'apenas marca regional', 'construção erudita'], a: 0 },
    { serie: '2ª EM', q: 'Em "vende-se casas", há um problema de concordância com o uso do "se":', opts: ['indevido, pois falta o plural no verbo', 'correto, pois o verbo concorda com casas', 'correto, pois se é pronome possessivo', 'indevido, pois nao existe voz passiva'], a: 0 },
  ],
  ciencias: [
    { serie: '6º EF', q: 'Qual gás as plantas absorvem na fotossíntese?', opts: ['Oxigênio', 'Nitrogênio', 'Gás carbônico', 'Hélio'], a: 2 },
    { serie: '4º EF', q: 'Qual órgão bombeia o sangue?', opts: ['Pulmão', 'Coração', 'Fígado', 'Estômago'], a: 1 },
    { serie: '4º EF', q: 'A água ferve a quantos graus ao nível do mar?', opts: ['100°C', '50°C', '90°C', '120°C'], a: 0 },
    { serie: '3º EF', q: 'Qual destes é um ser vivo?', opts: ['Pedra', 'Água', 'Cogumelo', 'Ar'], a: 2 },
    { serie: '2º EF', q: 'Qual parte da planta faz a fotossíntese?', opts: ['raiz', 'folha', 'tronco', 'fruto'], a: 1 },
    { serie: '3º EF', q: 'O ciclo da água inclui os processos de:', opts: ['evaporação, condensação e precipitação', 'fotossíntese e respiração', 'fermentação', 'polinização'], a: 0 },
    { serie: '4º EF', q: 'Qual sistema é responsável pela respiração?', opts: ['digestório', 'respiratório', 'circulatório', 'locomotor'], a: 1 },
    { serie: '5º EF', q: 'As proteínas são importantes para:', opts: ['o crescimento e a construção do corpo', 'dar energia rápida', 'colorir os alimentos', 'nada específico'], a: 0 },
    { serie: '6º EF', q: 'A célula responsável por conduzir impulsos nervosos é o:', opts: ['neurônio', 'glóbulo vermelho', 'músculo', 'óvulo'], a: 0 },
    { serie: '7º EF', q: 'A digestão dos alimentos começa na:', opts: ['boca', 'estômago', 'intestino', 'garganta'], a: 0 },
    { serie: '8º EF', q: 'Os pulmões são protegidos pela caixa torácica, formada pelas:', opts: ['costelas', 'vértebras', 'clavículas', 'pélvis'], a: 0 },
    { serie: '8º EF', q: 'O mineral que dá rigidez aos ossos é o:', opts: ['cálcio', 'ferro', 'sódio', 'potássio'], a: 0 },
    { serie: '9º EF', q: 'O aumento do gás carbônico na atmosfera intensifica:', opts: ['o efeito estufa', 'a camada de ozônio', 'a fotossíntese', 'a respiração das plantas'], a: 0 },
    { serie: '9º EF', q: 'A energia nuclear é obtida a partir da:', opts: ['fissão do átomo', 'queima de carvão', 'força do vento', 'água corrente'], a: 0 },
    { serie: '3ª EM', q: 'No Sistema Internacional de Unidades, a força é medida em:', opts: ['newton', 'joule', 'watt', 'pascal'], a: 0 },
    { serie: '3ª EM', q: 'Uma reação que libera calor é chamada de:', opts: ['exotérmica', 'endotérmica', 'isotérmica', 'adiabática'], a: 0 },
    { serie: '6º EF', q: 'As células procarióticas se diferenciam por:', opts: ['não ter núcleo organizado', 'ter parede celular', 'ser pluricelulares', 'fazer fotossíntese'], a: 0 },
    { serie: '6º EF', q: 'O tecido que reveste o corpo e os órgãos é o:', opts: ['epitelial', 'muscular', 'nervoso', 'ósseo'], a: 0 },
    { serie: '7º EF', q: 'O vírus NÃO é considerado célula porque:', opts: ['não tem organização celular completa', 'é muito pequeno', 'não causa doenças', 'vive apenas no ar'], a: 0 },
    { serie: '7º EF', q: 'A vacina estimula o organismo a produzir:', opts: ['anticorpos', 'toxinas', 'bactérias', 'vírus'], a: 0 },
    { serie: '8º EF', q: 'Uma solução ácida tem pH:', opts: ['menor que 7', 'igual a 7', 'maior que 7', 'sempre igual a zero'], a: 0 },
    { serie: '8º EF', q: 'A evaporação é a passagem:', opts: ['do estado líquido para o gasoso', 'do sólido para o líquido', 'do gasoso para o líquido', 'do sólido para o gasoso'], a: 0 },
    { serie: '9º EF', q: 'O modelo atômico de Rutherford propôs:', opts: ['a existência de núcleo e eletrosfera', 'esferas maciças indivisíveis', 'nuvem eletrônica sem núcleo', 'o átomo como menor parte sem estrutura'], a: 0 },
    { serie: '9º EF', q: 'A partícula de carga negativa é o:', opts: ['elétron', 'próton', 'nêutron', 'fóton'], a: 0 },
    { serie: '9º EF', q: 'A lei da gravitação universal foi formulada por:', opts: ['Newton', 'Einstein', 'Dalton', 'Galileu'], a: 0 },
    { serie: '1ª EM', q: 'A unidade de energia no Sistema Internacional é o:', opts: ['joule', 'watt', 'newton', 'pascal'], a: 0 },
    { serie: '1ª EM', q: 'O processo que libera energia a partir de alimentos na célula é a:', opts: ['respiração celular', 'fotossíntese', 'digestão externa', 'fermentação alcoólica'], a: 0 },
    { serie: '2ª EM', q: 'Na cadeia alimentar, o produtor é:', opts: ['quem produz seu próprio alimento', 'quem come plantas', 'quem caça outros animais', 'quem recicla nutrientes'], a: 0 },
    { serie: '2ª EM', q: 'Os seres que reciclam a matéria orgânica na natureza são os:', opts: ['decompositores', 'produtores', 'consumidores primários', 'herbívoros'], a: 0 },
    { serie: '3ª EM', q: 'Na genética, o genótipo é:', opts: ['a constituição genética do indivíduo', 'a aparência visível', 'o número de genes', 'o ambiente em que vive'], a: 0 },
    { serie: '3ª EM', q: 'A reprodução assexuada caracteriza-se por:', opts: ['um único progenitor sem gametas', 'dois progenitores', 'formação de gametas', 'troca de material genético'], a: 0 },
    { serie: '3ª EM', q: 'O coração humano tem quantas cavidades?', opts: ['4', '2', '3', '6'], a: 0 },
    { serie: '1ª EM', q: 'A camada de ozônio protege o planeta contra:', opts: ['a radiação ultravioleta', 'as chuvas ácidas', 'os ventos fortes', 'os raios X'], a: 0 },
    { serie: '2ª EM', q: 'A insulina é o hormônio que regula:', opts: ['a glicose no sangue', 'o oxigênio no ar', 'os glóbulos vermelhos', 'a pressão atmosférica'], a: 0 },
  ],
  historia: [
    { serie: '8º EF', q: 'Quem proclamou a independência do Brasil?', opts: ['Dom Pedro I', 'Tiradentes', 'Marechal Deodoro', 'Dom Pedro II'], a: 0 },
    { serie: '4º EF', q: 'Em que ano o Brasil foi "descoberto" pelos portugueses?', opts: ['1500', '1822', '1889', '1808'], a: 0 },
    { serie: '6º EF', q: 'Qual povo construiu as pirâmides do Egito?', opts: ['Romanos', 'Gregos', 'Egípcios', 'Astecas'], a: 2 },
    { serie: '3º EF', q: 'O que é uma linha do tempo?', opts: ['Um mapa de cidades', 'Uma organização de eventos em ordem cronológica', 'Uma tabela de preços', 'Um relógio de sol'], a: 1 },
    { serie: '2º EF', q: 'Qual destes é um tipo de moradia?', opts: ['iglu', 'bicicleta', 'caderno', 'ônibus'], a: 0 },
    { serie: '3º EF', q: 'O que usamos para marcar a passagem do tempo?', opts: ['calendário', 'bússola', 'mapa', 'régua'], a: 0 },
    { serie: '4º EF', q: 'Os povos indígenas brasileiros já moravam aqui antes de 1500. Isso significa que:', opts: ['eles são os povos originários do Brasil', 'eles vieram da Europa', 'eles chegaram depois de 1500', 'eles não existiam'], a: 0 },
    { serie: '5º EF', q: 'A escravidão foi oficialmente abolida no Brasil em:', opts: ['1888', '1822', '1500', '1789'], a: 0 },
    { serie: '6º EF', q: 'As estradas e os aquedutos da Roma Antiga mostram:', opts: ['engenharia e organização', 'que não havia cidades', 'que viviam em cavernas', 'que não faziam comércio'], a: 0 },
    { serie: '7º EF', q: 'O Renascimento valorizou:', opts: ['as artes e as ciências', 'a vida apenas no campo', 'o isolamento dos países', 'a guerra como única meta'], a: 0 },
    { serie: '8º EF', q: 'A vinda da família real ao Brasil ocorreu em:', opts: ['1808', '1822', '1889', '1900'], a: 0 },
    { serie: '8º EF', q: 'A Independência do Brasil aconteceu:', opts: ['em 1822, proclamada por Dom Pedro I', 'em 1888, por Marechal Deodoro', 'em 1500, por Cabral', 'em 1889, pela princesa Isabel'], a: 0 },
    { serie: '9º EF', q: 'A lei que aboliu a escravidão no Brasil foi assinada pela:', opts: ['princesa Isabel', 'Dom Pedro II', 'Getúlio Vargas', 'Dom Pedro I'], a: 0 },
    { serie: '9º EF', q: 'A Revolução Industrial teve início na:', opts: ['Inglaterra', 'França', 'Brasil', 'Itália'], a: 0 },
    { serie: '9º EF', q: 'A Segunda Guerra Mundial terminou em:', opts: ['1945', '1939', '1918', '1950'], a: 0 },
    { serie: '3ª EM', q: 'A globalização é caracterizada por:', opts: ['intensa integração econômica e cultural', 'isolamento dos países', 'redução das tecnologias', 'fim das migrações'], a: 0 },
    { serie: '6º EF', q: 'A Pré-história é dividida em:', opts: ['Paleolítico e Neolítico', 'Idade Média', 'Idade Moderna', 'Grandes Navegações'], a: 0 },
    { serie: '6º EF', q: 'A escrita foi criada principalmente para:', opts: ['registrar a administração e o comércio', 'decorar templos', 'passar o tempo', 'proibir palavras'], a: 0 },
    { serie: '7º EF', q: 'O feudalismo baseava-se em:', opts: ['relações de suserania e vassalagem', 'escravidão industrial', 'economia de mercado', 'liberdade total'], a: 0 },
    { serie: '7º EF', q: 'As Cruzadas foram:', opts: ['expedições religiosas à Terra Santa', 'guerras internas da Grécia', 'descobertas astronômicas', 'rotas de especiarias'], a: 0 },
    { serie: '8º EF', q: 'A Inconfidência Mineira (1789) defendia:', opts: ['a separação de Minas de Portugal', 'o retorno da corte para Portugal', 'a vinda da família real', 'o domínio francês'], a: 0 },
    { serie: '8º EF', q: 'O café foi essencial na economia brasileira no século:', opts: ['XIX', 'XVI', 'XIV', 'XXI'], a: 0 },
    { serie: '9º EF', q: 'A República foi proclamada no Brasil em:', opts: ['1889', '1822', '1888', '1894'], a: 0 },
    { serie: '9º EF', q: 'A Era Vargas (1930-1945) ficou marcada por:', opts: ['leis trabalhistas, como a CLT', 'campanhas abolicionistas', 'guerras guaranis', 'expedições bandeirantes'], a: 0 },
    { serie: '9º EF', q: 'O golpe militar de 1964 deu início a um período de:', opts: ['ditadura', 'redemocratização', 'monarquia', 'colônia de novo'], a: 0 },
    { serie: '9º EF', q: 'A Ditadura Militar terminou em:', opts: ['1985', '1964', '1979', '1993'], a: 0 },
    { serie: '1ª EM', q: 'A Revolução Francesa (1789) defendia:', opts: ['liberdade, igualdade e fraternidade', 'a monarquia absoluta', 'o feudalismo', 'o império colonial'], a: 0 },
    { serie: '1ª EM', q: 'As Grandes Navegações foram impulsionadas por:', opts: ['a busca de novas rotas comerciais', 'invenções científicas por acaso', 'o crescimento do feudalismo', 'guerras religiosas locais'], a: 0 },
    { serie: '2ª EM', q: 'A Primeira Guerra Mundial (1914-1918) teve como estopim:', opts: ['o assassinato do arquiduque Francisco Ferdinando', 'a quebra da Bolsa de Nova York', 'a invasão da Polônia', 'a queda do Muro de Berlim'], a: 0 },
    { serie: '2ª EM', q: 'A Revolução Russa de 1917 levou ao poder:', opts: ['os bolcheviques', 'a nobreza czarista', 'os monarquistas', 'os militares alemães'], a: 0 },
    { serie: '3ª EM', q: 'A Guerra Fria foi marcada pela disputa entre:', opts: ['EUA e URSS', 'Inglaterra e França', 'Alemanha e Itália', 'China e Japão'], a: 0 },
    { serie: '3ª EM', q: 'A queda do Muro de Berlim ocorreu em:', opts: ['1989', '1991', '1979', '2001'], a: 0 },
    { serie: '1ª EM', q: 'O Absolutismo concentrava o poder:', opts: ['nas mãos do monarca', 'no parlamento', 'no povo', 'no clero exclusivamente'], a: 0 },
    { serie: '2ª EM', q: 'O imperialismo europeu do século XIX buscava:', opts: ['expandir mercados e colônias', 'reduzir o comércio', 'preservar culturas locais', 'unificar as Américas'], a: 0 },
  ],
  geografia: [
    { serie: '4º EF', q: 'Qual é o maior oceano do planeta?', opts: ['Atlântico', 'Índico', 'Pacífico', 'Ártico'], a: 2 },
    { serie: '4º EF', q: 'Quantos continentes existem?', opts: ['5', '6', '7', '8'], a: 2 },
    { serie: '5º EF', q: 'Qual instrumento indica os pontos cardeais?', opts: ['Termômetro', 'Bússola', 'Barômetro', 'Telescópio'], a: 1 },
    { serie: '5º EF', q: 'Qual é a capital do Brasil?', opts: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'], a: 2 },
    { serie: '2º EF', q: 'Qual destes objetos ajuda a se orientar?', opts: ['bússola', 'lanterna', 'mochila', 'corda'], a: 0 },
    { serie: '3º EF', q: 'Os pontos cardeais são:', opts: ['norte, sul, leste e oeste', 'cima, baixo, esquerda e direita', 'inverno, verão, outono', 'pequeno, médio e grande'], a: 0 },
    { serie: '4º EF', q: 'A camada de ar que envolve a Terra é a:', opts: ['atmosfera', 'hidrosfera', 'litosfera', 'biosfera'], a: 0 },
    { serie: '5º EF', q: 'O Brasil é dividido em:', opts: ['26 estados e o Distrito Federal', '50 estados', '10 províncias', 'apenas 3 regiões'], a: 0 },
    { serie: '6º EF', q: 'O movimento de rotação da Terra é responsável por:', opts: ['dias e noites', 'as estações do ano', 'as marés', 'os eclipses'], a: 0 },
    { serie: '6º EF', q: 'O Brasil está localizado em qual continente?', opts: ['América do Sul', 'América do Norte', 'Europa', 'África'], a: 0 },
    { serie: '7º EF', q: 'A maior floresta tropical do mundo é a:', opts: ['Amazônica', 'Atlântica', 'Siberiana', 'Caatinga'], a: 0 },
    { serie: '8º EF', q: 'O tempo refere-se às condições atmosféricas:', opts: ['de um dado momento', 'médias de muitos anos', 'do relevo da região', 'da vegetação local'], a: 0 },
    { serie: '8º EF', q: 'Numa escala de mapa 1:100.000, cada 1 cm no mapa equivale a:', opts: ['1 km real', '100 km reais', '10 m reais', '1000 km reais'], a: 0 },
    { serie: '9º EF', q: 'Uma das principais causas do desmatamento na Amazônia é:', opts: ['a expansão da agropecuária', 'a queda de meteoros', 'a poluição do mar', 'os invernos rigorosos'], a: 0 },
    { serie: '9º EF', q: 'O principal bioma do Centro-Oeste brasileiro é o:', opts: ['cerrado', 'mata atlântica', 'caatinga', 'pampa'], a: 0 },
    { serie: '3ª EM', q: 'A urbanização acelerada no Brasil gerou:', opts: ['crescimento de problemas sociais e ambientais', 'o fim das cidades', 'o aumento da área rural', 'a redução da população'], a: 0 },
    { serie: '6º EF', q: 'A hidrosfera corresponde:', opts: ['à água do planeta', 'ao ar', 'às rochas', 'aos seres vivos'], a: 0 },
    { serie: '6º EF', q: 'Os rios brasileiros deságuam principalmente:', opts: ['no oceano Atlântico', 'no Pacífico', 'no Índico', 'no Ártico'], a: 0 },
    { serie: '7º EF', q: 'A região brasileira com o maior número de estados é:', opts: ['Nordeste', 'Sul', 'Centro-Oeste', 'Sudeste'], a: 0 },
    { serie: '7º EF', q: 'O clima equatorial ocorre principalmente na região:', opts: ['Norte (Amazônia)', 'Sul', 'Nordeste', 'Sudeste'], a: 0 },
    { serie: '8º EF', q: 'Os mapas temáticos podem representar:', opts: ['população, relevo e clima', 'apenas ruas de uma cidade', 'apenas um país', 'somente oceanos'], a: 0 },
    { serie: '8º EF', q: 'A migração é:', opts: ['o deslocamento de pessoas entre lugares', 'a troca de mercadorias', 'um tipo de clima', 'o nome de um rio'], a: 0 },
    { serie: '9º EF', q: 'A industrialização brasileira concentrou-se inicialmente na região:', opts: ['Sudeste', 'Norte', 'Sul', 'Centro-Oeste'], a: 0 },
    { serie: '9º EF', q: 'A maior parte da energia elétrica do Brasil vem de:', opts: ['hidrelétricas', 'usinas eólicas', 'usinas nucleares', 'painéis solares'], a: 0 },
    { serie: '9º EF', q: 'Nas últimas décadas, o crescimento populacional brasileiro:', opts: ['diminuiu em ritmo', 'dobrou', 'estagnou em zero', 'aumentou muito sempre'], a: 0 },
    { serie: '9º EF', q: 'O IDH avalia:', opts: ['educação, renda e saúde', 'apenas a renda', 'só o clima', 'apenas a população'], a: 0 },
    { serie: '1ª EM', q: 'A urbanização é o processo de:', opts: ['crescimento das cidades', 'esvaziamento das cidades', 'aumento da área rural', 'diminuição da população absoluta'], a: 0 },
    { serie: '1ª EM', q: 'O grupo BRICS é formado por:', opts: ['Brasil, Rússia, Índia, China e África do Sul', 'Brasil, Egito, Suécia e Japão', 'Brasil, México e Chile', 'Canadá, EUA e México'], a: 0 },
    { serie: '2ª EM', q: 'A globalização aproxima os países por meio de:', opts: ['fluxos econômicos e digitais', 'barreiras e muros', 'isolamento comercial', 'impostos proibitivos sempre'], a: 0 },
    { serie: '2ª EM', q: 'A pecuária extensiva caracteriza-se por:', opts: ['criação em grandes áreas com pouca tecnologia', 'uso intensivo de tecnologia', 'animais criados em cidades', 'criação apenas de aves'], a: 0 },
    { serie: '3ª EM', q: 'O geoprocessamento utiliza:', opts: ['satélites e sistemas de informação geográfica', 'apenas mapas antigos', 'bússolas tradicionais', 'réguas simples'], a: 0 },
    { serie: '3ª EM', q: 'A emissão de gases do efeito estufa está ligada principalmente:', opts: ['à queima de combustíveis fósseis', 'ao plantio de árvores', 'à reciclagem', 'às chuvas regulares'], a: 0 },
    { serie: '1ª EM', q: 'A bacia Amazônica é considerada:', opts: ['a maior bacia hidrográfica do mundo', 'a menor bacia do Brasil', 'uma bacia do Nordeste', 'um lago do Sul'], a: 0 },
    { serie: '2ª EM', q: 'O agronegócio brasileiro se destaca como:', opts: ['grande exportador de commodities', 'importador de alimentos básicos', 'setor sem tecnologia', 'produtor apenas do mercado interno'], a: 0 },
  ],
  arte: [
    { serie: '2º EF', q: 'Quais são as cores primárias?', opts: ['Verde, laranja e roxo', 'Vermelho, azul e amarelo', 'Preto, branco e cinza', 'Rosa, turquesa e lilás'], a: 1 },
    { serie: '3ª EM', q: 'Leonardo da Vinci pintou:', opts: ['O Grito', 'Mona Lisa', 'Noite Estrelada', 'Abaporu'], a: 1 },
    { serie: '5º EF', q: 'O que é uma escultura?', opts: ['Uma pintura em papel', 'Uma obra de arte em três dimensões', 'Um desenho a lápis', 'Uma fotografia'], a: 1 },
    { serie: '3º EF', q: 'Ritmo, melodia e harmonia são elementos de:', opts: ['Pintura', 'Escultura', 'Música', 'Dança'], a: 2 },
    { serie: '1º EF', q: 'Qual instrumento usamos para pintar?', opts: ['pincel', 'microfone', 'teclado', 'régua'], a: 0 },
    { serie: '2º EF', q: 'As cores secundárias são formadas pela mistura de:', opts: ['duas cores primárias', 'preto e branco', 'três cores iguais', 'luz e água'], a: 0 },
    { serie: '3º EF', q: 'Profissional que cria esculturas é o:', opts: ['escultor', 'pintor', 'músico', 'dançarino'], a: 0 },
    { serie: '4º EF', q: 'O teatro utiliza principalmente:', opts: ['o corpo e a voz', 'pincéis e tintas', 'martelos e pregos', 'calculadoras'], a: 0 },
    { serie: '5º EF', q: 'São cores frias:', opts: ['azul e verde', 'vermelho e amarelo', 'preto e branco', 'laranja e roxo'], a: 0 },
    { serie: '6º EF', q: 'Na fotografia, o enquadramento serve para:', opts: ['escolher o que aparece na imagem', 'apagar fotos', 'corrigir o som', 'desenhar letras'], a: 0 },
    { serie: '7º EF', q: 'O grupo de bailarinos que dança junto é o:', opts: ['corpo de baile', 'plateia', 'cenário', 'fotógrafo'], a: 0 },
    { serie: '8º EF', q: 'A Semana de Arte Moderna de 1922 ocorreu em:', opts: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'], a: 0 },
    { serie: '9º EF', q: 'A obra "Abaporu", de Tarsila do Amaral, pertence ao:', opts: ['modernismo', 'barroco', 'renascimento', 'impressionismo'], a: 0 },
    { serie: '9º EF', q: 'O impressionismo valorizava:', opts: ['a luz e as cores ao ar livre', 'apenas a arte religiosa', 'formas geométricas exatas', 'a cópia de fotografias'], a: 0 },
    { serie: '3ª EM', q: 'O grafite é reconhecido como:', opts: ['uma linguagem da arte urbana', 'somente um ato de vandalismo', 'uma invenção do século 21', 'um artesanato indígena'], a: 0 },
    { serie: '3º EF', q: 'Faz parte de um espetáculo de dança:', opts: ['a coreografia', 'a receita', 'o relatório', 'o gráfico'], a: 0 },
    { serie: '6º EF', q: 'As artes visuais incluem:', opts: ['pintura, desenho e escultura', 'apenas música', 'poesia somente', 'dança somente'], a: 0 },
    { serie: '6º EF', q: 'Os elementos básicos das artes visuais são:', opts: ['ponto, linha, forma e cor', 'ritmo e melodia', 'sabor e cheiro', 'do e re'], a: 0 },
    { serie: '6º EF', q: 'O artista que cria imagens com recursos digitais trabalha com:', opts: ['arte digital', 'aquarela', 'mosaico', 'gravura'], a: 0 },
    { serie: '7º EF', q: 'A perspectiva serve para dar:', opts: ['profundidade à imagem', 'ritmo', 'cor', 'som'], a: 0 },
    { serie: '7º EF', q: 'Na música, o compasso organiza:', opts: ['os pulsos e o tempo', 'apenas as letras', 'as cores', 'a iluminação'], a: 0 },
    { serie: '8º EF', q: 'O curta-metragem é:', opts: ['uma produção audiovisual curta', 'uma pintura mural', 'um poema', 'um romance'], a: 0 },
    { serie: '8º EF', q: 'No teatro, a luz, o cenário e o figurino compõem:', opts: ['a linguagem cênica', 'o roteiro escrito', 'a plateia', 'a bilheteria'], a: 0 },
    { serie: '9º EF', q: 'A arte abstrata caracteriza-se por:', opts: ['fugir da representação figurativa da realidade', 'copiar a realidade com detalhes', 'ser exclusivamente religiosa', 'usar só palavras'], a: 0 },
    { serie: '9º EF', q: 'A diversidade cultural brasileira inclui o artesanato:', opts: ['indígena, quilombola e ribeirinho', 'apenas europeu', 'somente industrial', 'de um único povo'], a: 0 },
    { serie: '1ª EM', q: 'A cultura de massa é produzida principalmente:', opts: ['pela indústria cultural', 'pelos artistas locais', 'pela escola', 'somente pelo Estado'], a: 0 },
    { serie: '1ª EM', q: 'A performance utiliza como suporte principalmente:', opts: ['o corpo e o tempo', 'a tela e o pincel', 'mármore e cinzel', 'o piano'], a: 0 },
    { serie: '2ª EM', q: 'As vanguardas europeias do início do século XX incluem:', opts: ['cubismo, futurismo e surrealismo', 'renascimento e barroco', 'arte medieval', 'arte clássica'], a: 0 },
    { serie: '2ª EM', q: 'A fotografia surgiu no século:', opts: ['XIX', 'XV', 'XXI', 'XII'], a: 0 },
    { serie: '3ª EM', q: 'A Estética é a área da filosofia que estuda:', opts: ['o belo e a experiência artística', 'apenas a pintura', 'somente o som', 'as formas de comércio'], a: 0 },
    { serie: '3ª EM', q: 'O patrimônio cultural imaterial inclui:', opts: ['festas, saberes e tradições', 'apenas prédios', 'somente obras em museus', 'monumentos internacionais'], a: 0 },
    { serie: '3ª EM', q: 'Na organização de exposições, a curadoria é a função de:', opts: ['selecionar e organizar as obras', 'pintar o teto do museu', 'vender ingressos', 'limpar as salas'], a: 0 },
    { serie: '1ª EM', q: 'A arte indígena brasileira representa:', opts: ['valores e cosmologias dos povos', 'apenas decoração', 'réplicas europeias', 'arte industrial'], a: 0 },
    { serie: '2ª EM', q: 'O cinema, as séries e o streaming configuram:', opts: ['indústrias audiovisuais', 'apenas lazer passivo', 'formas de impressão', 'artesanato'], a: 0 },
  ],
  educacao_fisica: [
    { serie: '7º EF', q: 'Qual esporte se joga com 5 jogadores por time na quadra?', opts: ['Futebol', 'Basquete', 'Vôlei', 'Tênis'], a: 1 },
    { serie: '5º EF', q: 'O aquecimento antes do exercício serve para:', opts: ['Cansar mais rápido', 'Preparar o corpo e evitar lesões', 'Aumentar o peso', 'Diminuir a respiração'], a: 1 },
    { serie: '3º EF', q: 'Qual habilidade é usada em quase todos os esportes?', opts: ['Coordenação motora', 'Cantar', 'Desenhar', 'Memorizar poemas'], a: 0 },
    { serie: '9º EF', q: 'Uma atividade aeróbica é:', opts: ['Corrida', 'Levantamento de peso máximo', 'Alongamento parado', 'Dormir'], a: 0 },
    { serie: '1º EF', q: 'Pular, correr e rolar são:', opts: ['movimentos do corpo', 'tipos de comida', 'cores', 'materiais escolares'], a: 0 },
    { serie: '2º EF', q: 'Durante a aula de educação física, o correto é:', opts: ['beber água quando sentir sede', 'nunca beber água', 'beber apenas refrigerante', 'esperar terminar tudo para beber'], a: 0 },
    { serie: '4º EF', q: 'A brincadeira de esconde-esconde trabalha:', opts: ['atenção e velocidade', 'apenas força', 'apenas voz', 'memória de nomes'], a: 0 },
    { serie: '5º EF', q: 'O futebol é jogado principalmente com:', opts: ['os pés', 'somente as mãos', 'uma raquete', 'um taco'], a: 0 },
    { serie: '6º EF', q: 'No vôlei, cada equipe tem quantos jogadores em quadra?', opts: ['6', '5', '7', '11'], a: 0 },
    { serie: '6º EF', q: 'O alongamento deve ser feito:', opts: ['antes e depois dos exercícios', 'só depois de comer', 'nunca', 'apenas aos domingos'], a: 0 },
    { serie: '7º EF', q: 'A frequência cardíaca aumenta durante o exercício porque:', opts: ['o coração bombeia mais sangue para o corpo', 'o corpo esfria', 'os músculos encolhem', 'a respiração para'], a: 0 },
    { serie: '8º EF', q: 'O IMC serve para:', opts: ['avaliar a massa corporal em relação à altura', 'medir a força', 'contar passos', 'medir a flexibilidade'], a: 0 },
    { serie: '8º EF', q: 'Os esportes coletivos exigem principalmente:', opts: ['trabalho em equipe', 'isolamento', 'silêncio total', 'competição individual sempre'], a: 0 },
    { serie: '9º EF', q: 'A prática regular de atividade física ajuda a prevenir:', opts: ['doenças como obesidade e hipertensão', 'todas as doenças, sem exceção', 'apenas quebraduras', 'nada em especial'], a: 0 },
    { serie: '9º EF', q: 'Um bom treino inclui:', opts: ['aquecimento, atividade principal e volta à calma', 'apenas exercício pesado', 'só alongamento', 'nenhum descanso'], a: 0 },
    { serie: '3ª EM', q: 'O exercício anaeróbico é aquele que:', opts: ['exige alta intensidade e pouco oxigênio', 'é feito devagar', 'não movimenta o corpo', 'dura várias horas'], a: 0 },
    { serie: '6º EF', q: 'Para evitar lesões antes de um jogo, o ideal é:', opts: ['fazer aquecimento', 'dormir', 'comer muito', 'começar direto sem preparo'], a: 0 },
    { serie: '6º EF', q: 'No basquete, uma cesta pode valer:', opts: ['2 ou 3 pontos', '1 ponto sempre', '5 pontos', '6 pontos'], a: 0 },
    { serie: '7º EF', q: 'No vôlei, a equipe marca ponto também quando:', opts: ['o adversário comete erro', 'todos gritam', 'o árbitro apita', 'a plateia reclama'], a: 0 },
    { serie: '7º EF', q: 'A flexibilidade é desenvolvida principalmente com:', opts: ['alongamentos', 'levantamento de peso máximo', 'corridas longuíssimas', 'exercícios isométricos'], a: 0 },
    { serie: '8º EF', q: 'As capacidades físicas incluem:', opts: ['força, resistência, velocidade e flexibilidade', 'cor, tamanho e peso', 'altura, idade e peso', 'silêncio e calma'], a: 0 },
    { serie: '8º EF', q: 'Para o controle do peso corporal, é essencial:', opts: ['equilibrar ingestão e gasto de energia', 'jejum total', 'não se movimentar', 'comer apenas à noite'], a: 0 },
    { serie: '9º EF', q: 'O sedentarismo está associado a:', opts: ['doenças cardiovasculares e diabetes', 'músculos sempre maiores', 'imunidade absoluta', 'desempenho máximo'], a: 0 },
    { serie: '9º EF', q: 'O fair play significa:', opts: ['jogo limpo e respeito', 'jogar só para vencer', 'torcida agressiva', 'usar vantagens ilegais'], a: 0 },
    { serie: '9º EF', q: 'No futsal, cada equipe tem em quadra:', opts: ['5 jogadores', '11 jogadores', '7 jogadores', '10 jogadores'], a: 0 },
    { serie: '1ª EM', q: 'Os esportes olímpicos de verão incluem:', opts: ['atletismo, natação e ginástica', 'xadrez', 'pesca esportiva', 'esportes de gelo'], a: 0 },
    { serie: '1ª EM', q: 'Na musculação, o princípio da sobrecarga progressiva significa:', opts: ['aumentar gradualmente a carga', 'manter sempre o mesmo peso', 'diminuir sempre a carga', 'nunca descansar'], a: 0 },
    { serie: '2ª EM', q: 'O treinamento intervalado alterna:', opts: ['esforço e recuperação', 'só esforço contínuo', 'dieta e jejum', 'velocidade e peso'], a: 0 },
    { serie: '2ª EM', q: 'A frequência cardíaca em repouso tende a ser:', opts: ['menor em pessoas mais condicionadas', 'maior em quem treina muito', 'igual para todos', 'indiferente ao treino'], a: 0 },
    { serie: '3ª EM', q: 'O lazer ativo inclui:', opts: ['atividades que movimentam o corpo', 'assistir TV parado', 'dormir o dia todo', 'cozinhar sentado'], a: 0 },
    { serie: '3ª EM', q: 'A educação física adaptada atende:', opts: ['pessoas com deficiência', 'apenas atletas profissionais', 'só crianças pequenas', 'somente idosos'], a: 0 },
    { serie: '3ª EM', q: 'A pausa de recuperação no treino serve para:', opts: ['evitar o overtraining e recuperar o corpo', 'perder tempo', 'reduzir resultados', 'aquecer mais'], a: 0 },
    { serie: '1ª EM', q: 'O planejamento de um treino considera:', opts: ['objetivo, volume e intensidade', 'somente a idade', 'apenas o peso', 'só o dia da semana'], a: 0 },
    { serie: '2ª EM', q: 'As modalidades de esporte de raquete incluem:', opts: ['tênis, badminton e squash', 'natação e remo', 'levantamento de peso', 'dança clássica'], a: 0 },
  ],
  ingles: [
    { serie: '5º EF', q: 'Como se diz "obrigado" em inglês?', opts: ['Please', 'Thank you', 'Sorry', 'Hello'], a: 1 },
    { serie: '5º EF', q: 'Qual é a tradução de "cat"?', opts: ['Cachorro', 'Pássaro', 'Gato', 'Peixe'], a: 2 },
    { serie: '6º EF', q: 'Complete: "I ___ a student."', opts: ['is', 'are', 'am', 'be'], a: 2 },
    { serie: '7º EF', q: 'Qual dia da semana é "Friday"?', opts: ['Segunda', 'Quarta', 'Sexta', 'Domingo'], a: 2 },
    { serie: '1º EF', q: 'Como se diz "azul" em inglês?', opts: ['blue', 'green', 'red', 'black'], a: 0 },
    { serie: '2º EF', q: '"One, two, three" significa:', opts: ['1, 2, 3', '3, 2, 1', 'uma cidade', 'dois sapatos'], a: 0 },
    { serie: '3º EF', q: 'Qual é a cor vermelha em inglês?', opts: ['red', 'white', 'blue', 'yellow'], a: 0 },
    { serie: '4º EF', q: 'A palavra "school" significa:', opts: ['escola', 'piscina', 'festa', 'trabalho'], a: 0 },
    { serie: '5º EF', q: 'A tradução de "good morning" é:', opts: ['bom dia', 'boa noite', 'boa tarde', 'desculpe'], a: 0 },
    { serie: '6º EF', q: 'Complete: "They ___ playing soccer."', opts: ['are', 'is', 'am', 'be'], a: 0 },
    { serie: '7º EF', q: 'O plural de "child" é:', opts: ['children', 'childs', 'childes', 'childrens'], a: 0 },
    { serie: '8º EF', q: 'Complete: "Does she ___ coffee?"', opts: ['like', 'likes', 'liking', 'liked'], a: 0 },
    { serie: '9º EF', q: 'Complete: "I ___ to school yesterday."', opts: ['went', 'go', 'gone', 'goes'], a: 0 },
    { serie: '9º EF', q: 'O passado do verbo "buy" é:', opts: ['bought', 'buyed', 'boughted', 'buys'], a: 0 },
    { serie: '3ª EM', q: 'Complete: "If I ___ rich, I would travel."', opts: ['were', 'was', 'am', 'be'], a: 0 },
    { serie: '3ª EM', q: 'Um sinônimo de "happy" é:', opts: ['glad', 'sad', 'angry', 'tired'], a: 0 },
    { serie: '6º EF', q: 'A palavra "favorite" significa:', opts: ['favorito', 'temperatura', 'família', 'comparativo'], a: 0 },
    { serie: '6º EF', q: 'Complete: "She ___ a doctor."', opts: ['is', 'are', 'am', 'be'], a: 0 },
    { serie: '7º EF', q: '"Yesterday" significa:', opts: ['ontem', 'amanhã', 'hoje', 'sempre'], a: 0 },
    { serie: '7º EF', q: 'Complete: "I ___ two brothers."', opts: ['have', 'has', 'am', 'is'], a: 0 },
    { serie: '8º EF', q: 'O comparativo de "big" é:', opts: ['bigger', 'bigest', 'more big', 'bigget'], a: 0 },
    { serie: '8º EF', q: 'Complete: "She is ___ than me."', opts: ['taller', 'tallest', 'more tall', 'as tall'], a: 0 },
    { serie: '9º EF', q: 'Complete: "He has lived here ___ 2010."', opts: ['since', 'for', 'from', 'at'], a: 0 },
    { serie: '9º EF', q: 'Complete: "I ___ my homework already."', opts: ['have done', 'did', 'do', 'done'], a: 0 },
    { serie: '1ª EM', q: 'Complete: "If it rains, I ___ stay home."', opts: ['will', 'would', 'can', 'going to'], a: 0 },
    { serie: '1ª EM', q: '"Health" significa:', opts: ['saúde', 'calor', 'herança', 'ajuda'], a: 0 },
    { serie: '2ª EM', q: 'Complete na voz passiva: "The letter ___ by Ana."', opts: ['was written', 'wrote', 'writes', 'is write'], a: 0 },
    { serie: '2ª EM', q: '"Despite" significa:', opts: ['apesar de', 'depois de', 'antes de', 'por causa de'], a: 0 },
    { serie: '3ª EM', q: 'Complete: "I wish I ___ more time."', opts: ['had', 'have', 'has', 'having'], a: 0 },
    { serie: '3ª EM', q: '"Had been working" está no tempo:', opts: ['past perfect continuous', 'present continuous', 'simple past', 'future perfect'], a: 0 },
    { serie: '3ª EM', q: 'Complete: "If I had studied, I ___ passed."', opts: ['would have', 'will', 'would', 'have'], a: 0 },
    { serie: '3ª EM', q: 'A palavra "understanding" significa:', opts: ['compreensão', 'subterrâneo', 'aprendizagem', 'melodia'], a: 0 },
    { serie: '1ª EM', q: 'Complete: "Take an umbrella. It ___ later."', opts: ['might rain', 'rains', 'rained', 'is to rain'], a: 0 },
    { serie: '2ª EM', q: 'Complete: "I have been studying ___ two hours."', opts: ['for', 'since', 'from', 'at'], a: 0 },
  ],
  ensino_religioso: [
    { serie: '5º EF', q: 'Qual valor é comum às grandes tradições religiosas?', opts: ['Ódio', 'Respeito e solidariedade', 'Indiferença', 'Egoísmo'], a: 1 },
    { serie: '6º EF', q: 'O que é empatia?', opts: ['Fingir sentimentos', 'Colocar-se no lugar do outro', 'Não ouvir ninguém', 'Gritar mais alto'], a: 1 },
    { serie: '4º EF', q: 'Quem é reverenciado como mestre em várias religiões?', opts: ['Uma montanha', 'Pessoas que ensinam o bem', 'Um animal', 'Uma tempestade'], a: 1 },
    { serie: '9º EF', q: 'A liberdade religiosa garante:', opts: ['Obrigar todos a crer igual', 'Cada um seguir suas crenças com respeito', 'Proibir orações', 'Criar conflitos'], a: 1 },
    { serie: '1º EF', q: 'Compartilhar o lanche com o colega é um ato de:', opts: ['amizade e generosidade', 'egoísmo', 'raiva', 'desrespeito'], a: 0 },
    { serie: '3º EF', q: 'A convivência fica melhor quando:', opts: ['respeitamos as diferenças', 'humilhamos os outros', 'gritamos mais alto', 'não ouvimos ninguém'], a: 0 },
    { serie: '4º EF', q: 'As histórias sagradas ensinam principalmente:', opts: ['valores como bondade e fé', 'técnicas de guerra', 'apenas magias', 'fórmulas matemáticas'], a: 0 },
    { serie: '5º EF', q: 'Solidariedade significa:', opts: ['ajudar quem precisa', 'ignorar o próximo', 'só pensar em si', 'pisotear os outros'], a: 0 },
    { serie: '6º EF', q: 'Dialogar sobre diferentes religiões é importante para:', opts: ['promover respeito e paz', 'convencer os outros', 'proibir crenças', 'apagar culturas'], a: 0 },
    { serie: '7º EF', q: 'A Constituição brasileira garante:', opts: ['a liberdade de consciência e de crença', 'o fim de todas as religiões', 'uma religião oficial', 'cobrança para crer'], a: 0 },
    { serie: '8º EF', q: 'Discriminar alguém pela religião fere:', opts: ['a dignidade da pessoa', 'apenas as leis de trânsito', 'o clima', 'a moda'], a: 0 },
    { serie: '9º EF', q: 'As tradições religiosas indígenas e afro-brasileiras fazem parte:', opts: ['da diversidade cultural do Brasil', 'apenas da África', 'de invenções recentes', 'de culturas proibidas'], a: 0 },
    { serie: '9º EF', q: 'A convivência pacífica entre crenças diferentes é chamada de:', opts: ['diálogo inter-religioso', 'fundamentalismo', 'proselitismo forçado', 'segregação'], a: 0 },
    { serie: '8º EF', q: 'Pelo princípio da laicidade do Estado:', opts: ['o Estado não adota religião oficial', 'o Estado apoia apenas uma fé', 'todos devem seguir uma única crença', 'as igrejas governam'], a: 0 },
    { serie: '3ª EM', q: 'Preservar o patrimônio cultural religioso ajuda a manter:', opts: ['a memória e a identidade dos povos', 'apenas prédios vazios', 'a velocidade das cidades', 'o valor dos impostos'], a: 0 },
    { serie: '1º EF', q: 'Quando um colega cai, o primeiro a fazer é:', opts: ['ajudá-lo e chamar um adulto', 'rir dele', 'ignorar', 'sair correndo'], a: 0 },
    { serie: '6º EF', q: 'Respeitar crenças diferentes das nossas se chama:', opts: ['tolerância religiosa', 'fanatismo', 'indiferença', 'conflito'], a: 0 },
    { serie: '6º EF', q: 'Os símbolos religiosos comunicam:', opts: ['valores e tradições das comunidades', 'apenas enfeites', 'segredos proibidos', 'sinais de perigo'], a: 0 },
    { serie: '6º EF', q: 'Reconhecer e aceitar o outro é base para:', opts: ['a convivência pacífica', 'o isolamento', 'a rivalidade', 'o medo'], a: 0 },
    { serie: '7º EF', q: 'As matrizes religiosas presentes no Brasil incluem:', opts: ['a indígena, a africana e a ocidental', 'apenas a oriental', 'somente a europeia', 'uma única matriz'], a: 0 },
    { serie: '7º EF', q: 'O rito é:', opts: ['um conjunto de práticas simbólicas de uma tradição', 'uma proibição alimentar', 'um templo sagrado', 'um alimento ritual'], a: 0 },
    { serie: '8º EF', q: 'No Cristianismo e no Judaísmo, os textos sagrados incluem:', opts: ['a Bíblia e a Torá', 'apenas a Bíblia', 'somente o Alcorão', 'os Vedas'], a: 0 },
    { serie: '8º EF', q: 'A ética nas tradições religiosas orienta:', opts: ['condutas de respeito na convivência', 'apenas dietas', 'rituais secretos', 'regras de comércio'], a: 0 },
    { serie: '9º EF', q: 'A pluralidade religiosa numa turma de escola pede:', opts: ['respeito e diálogo entre todas as crenças', 'uniformizar as crenças', 'silêncio total sobre o tema', 'julgamento das diferenças'], a: 0 },
    { serie: '9º EF', q: 'Os Direitos Humanos garantem:', opts: ['liberdade de crença e consciência', 'obrigação de crer', 'uma religião oficial', 'proibição de novas religiões'], a: 0 },
    { serie: '1ª EM', q: 'A filosofia do fenômeno religioso busca:', opts: ['compreender as religiões com respeito', 'julgar os praticantes', 'substituir as religiões', 'proibir novas crenças'], a: 0 },
    { serie: '1ª EM', q: 'O diálogo inter-religioso ajuda a:', opts: ['reduzir preconceitos e conflitos', 'aumentar rivalidades', 'isolar os grupos', 'criar exclusões'], a: 0 },
    { serie: '2ª EM', q: 'O sagrado pode manifestar-se por meio de:', opts: ['lugares, objetos, pessoas e festas', 'apenas templos', 'somente livros', 'exclusivamente silêncio'], a: 0 },
    { serie: '2ª EM', q: 'Espiritualidade pode ser entendida como:', opts: ['busca pessoal de sentido e valores', 'tempo de folga todo mês', 'um tipo de dieta', 'uma característica física'], a: 0 },
    { serie: '3ª EM', q: 'Pela laicidade, o Estado brasileiro:', opts: ['é neutro em relação às religiões', 'financia apenas uma igreja', 'catequiza os cidadãos', 'exige templo em todo órgão público'], a: 0 },
    { serie: '3ª EM', q: 'As manifestações religiosas contemporâneas incluem:', opts: ['pluralismo e novas espiritualidades', 'fundamentalismo único', 'repressão das crenças', 'militarização'], a: 0 },
    { serie: '3ª EM', q: 'O ensino religioso na escola pública visa:', opts: ['a formação integral e a diversidade', 'a conversão', 'a catequese', 'apenas dar notas'], a: 0 },
    { serie: '1ª EM', q: 'Os povos originários do Brasil têm:', opts: ['suas próprias tradições espirituais', 'nenhuma espiritualidade', 'culturas importadas', 'apenas rituais modernos'], a: 0 },
    { serie: '2ª EM', q: 'Os direitos à diversidade religiosa aplicam-se:', opts: ['a todas as pessoas, com igualdade', 'somente às maiorias', 'apenas aos templos', 'somente aos maiores de idade'], a: 0 },
  ],
  matematica: [
    { serie: '2º EF', q: 'Quanto é 3 + 4?', opts: ['6', '7', '8', '9'], a: 1 },
    { serie: '2º EF', q: 'Qual número é o maior?', opts: ['32', '23', '11', '9'], a: 0 },
    { serie: '3º EF', q: 'Cinco dúzias correspondem a:', opts: ['60', '50', '55', '65'], a: 0 },
    { serie: '4º EF', q: 'Quanto é 7 × 8?', opts: ['54', '56', '48', '64'], a: 1 },
    { serie: '5º EF', q: 'Quanto é 450 ÷ 5?', opts: ['90', '80', '95', '85'], a: 0 },
    { serie: '5º EF', q: 'Um quarto de 20 é igual a:', opts: ['5', '4', '8', '10'], a: 0 },
    { serie: '6º EF', q: 'Quanto é 0,25 + 0,75?', opts: ['1', '1,5', '0,5', '1,25'], a: 0 },
    { serie: '6º EF', q: 'Um terço de 30 é igual a:', opts: ['10', '15', '9', '12'], a: 0 },
    { serie: '7º EF', q: 'Quanto é -5 + (-2)?', opts: ['-7', '-3', '7', '3'], a: 0 },
    { serie: '7º EF', q: 'Quanto é 20% de 80?', opts: ['16', '8', '20', '24'], a: 0 },
    { serie: '8º EF', q: 'Se x + 2 = 10, então x vale:', opts: ['8', '12', '5', '20'], a: 0 },
    { serie: '8º EF', q: 'O valor de 3 × 2 + 5 é:', opts: ['11', '21', '30', '16'], a: 0 },
    { serie: '9º EF', q: 'A raiz quadrada de 144 é:', opts: ['12', '14', '11', '13'], a: 0 },
    { serie: '9º EF', q: 'Resolva 2x - 10 = 4:', opts: ['x = 7', 'x = 6', 'x = 8', 'x = 14'], a: 0 },
    { serie: '3ª EM', q: 'Se f(x) = 3x + 2, então f(4) vale:', opts: ['14', '13', '12', '11'], a: 0 },
    { serie: '3ª EM', q: 'A média de 4, 8, 10 e 6 é:', opts: ['7', '28', '14', '9'], a: 0 },
    { serie: '6º EF', q: 'O dobro de 3/4 é:', opts: ['3/2', '6/8', '1', '3/8'], a: 0 },
    { serie: '6º EF', q: 'Quanto é 12 ÷ 0,5?', opts: ['24', '6', '60', '120'], a: 0 },
    { serie: '6º EF', q: 'Em 45 segundos, temos:', opts: ['0 min e 45 s', '45 min', '1 min e 45 s', '1 min'], a: 0 },
    { serie: '7º EF', q: 'Quanto é 2/5 de 25?', opts: ['10', '5', '20', '15'], a: 0 },
    { serie: '7º EF', q: 'Quanto é 30% de 150?', opts: ['45', '50', '40', '30'], a: 0 },
    { serie: '8º EF', q: 'Resolva 4x - 2 = 10:', opts: ['x = 3', 'x = 4', 'x = 2', 'x = 6'], a: 0 },
    { serie: '8º EF', q: 'Quanto é 8² - 3²?', opts: ['55', '64', '9', '40'], a: 0 },
    { serie: '9º EF', q: 'As raízes de x² - 4 = 0 são:', opts: ['2 e −2', '4 e −4', '0 e 4', '16'], a: 0 },
    { serie: '9º EF', q: 'Quanto é 0,2 × 0,3?', opts: ['0,06', '0,6', '6', '0,05'], a: 0 },
    { serie: '1ª EM', q: 'Na função f(x) = 2x + 1, quanto vale f(3)?', opts: ['7', '6', '8', '9'], a: 0 },
    { serie: '1ª EM', q: 'A progressão aritmética 2, 5, 8,... tem razão:', opts: ['3', '2', '5', '1'], a: 0 },
    { serie: '2ª EM', q: 'A soma dos ângulos internos de um octógono é:', opts: ['1080°', '1260°', '720°', '1440°'], a: 0 },
    { serie: '2ª EM', q: 'A equação x² + 1 = 0 no conjunto dos reais tem:', opts: ['nenhuma solução', 'uma solução', 'duas soluções', 'infinitas soluções'], a: 0 },
    { serie: '3ª EM', q: 'A derivada de f(x) = x² é:', opts: ['2x', 'x', '2', 'x³'], a: 0 },
    { serie: '3ª EM', q: 'O log10(1000) vale:', opts: ['3', '10', '100', '1'], a: 0 },
    { serie: '3ª EM', q: 'A probabilidade de tirar uma carta vermelha de um baralho é:', opts: ['1/2', '1/4', '1/3', '2/3'], a: 0 },
    { serie: '1ª EM', q: 'Uma das raízes de f(x) = x² - 2x - 3 é:', opts: ['x = 3', 'x = 6', 'x = -3', 'x = 2'], a: 0 },
    { serie: '2ª EM', q: 'A média geométrica de 2 e 8 é:', opts: ['4', '5', '16', '10'], a: 0 },
  ],
  matematica_2: [
    { serie: '5º EF', q: 'Se uma dúzia custa R$12, quanto custa uma unidade?', opts: ['R$2', 'R$1', 'R$0,50', 'R$12'], a: 1 },
    { serie: '5º EF', q: 'Quantos minutos há em 2 horas?', opts: ['60', '90', '120', '150'], a: 2 },
    { serie: '7º EF', q: 'O número 7 é:', opts: ['Primo', 'Par', 'Composto', 'Divisível por 2'], a: 0 },
    { serie: '5º EF', q: 'Quanto é 100 ÷ 4?', opts: ['20', '25', '50', '40'], a: 1 },
    { serie: '4º EF', q: 'Quanto é 9 × 9?', opts: ['81', '72', '63', '90'], a: 0 },
    { serie: '6º EF', q: 'Quanto é 2,5 + 1,25?', opts: ['3,75', '3,25', '2,75', '4,25'], a: 0 },
    { serie: '8º EF', q: 'Quanto é (-3) × (-4)?', opts: ['12', '-12', '7', '-7'], a: 0 },
    { serie: '9º EF', q: 'A expressão 2³ × 2² é igual a:', opts: ['32', '64', '16', '12'], a: 0 },
  ],
};

export const SUBJECT_STATIONS = [
  { id: 'portugues', label: 'Estação de Português', emoji: '📖', cat: 'portugues', subject: 'Língua Portuguesa', color: '#0ea5e9', p: [-18, 3] },
  { id: 'ciencias', label: 'Estação de Ciências', emoji: '🔬', cat: 'ciencias', subject: 'Ciências', color: '#10b981', p: [18, 3] },
  { id: 'historia', label: 'Estação de História', emoji: '🏛️', cat: 'historia', subject: 'História', color: '#f59e0b', p: [-18, 14] },
  { id: 'geografia', label: 'Estação de Geografia', emoji: '🌍', cat: 'geografia', subject: 'Geografia', color: '#ef4444', p: [18, 14] },
  { id: 'arte', label: 'Estação de Arte', emoji: '🎨', cat: 'arte', subject: 'Arte', color: '#ec4899', p: [-26, -12] },
  { id: 'educacao_fisica', label: 'Estação de Educação Física', emoji: '⚽', cat: 'educacao_fisica', subject: 'Educação Física', color: '#22c55e', p: [26, 9] },
  { id: 'ingles', label: 'Estação de Inglês', emoji: '🇬🇧', cat: 'ingles', subject: 'Língua Inglesa', color: '#6366f1', p: [6, -20] },
  { id: 'ensino_religioso', label: 'Estação de Ensino Religioso', emoji: '🕊️', cat: 'ensino_religioso', subject: 'Ensino Religioso', color: '#a855f7', p: [-6, 17] },
  { id: 'matematica', label: 'Estação de Matemática', emoji: '🧮', cat: 'final', subject: 'Matemática', color: '#7c3aed', p: [-29, 16] },
];

export const ARENA_ROUNDS = [
  { name: 'Frações', cat: 'fracoes', n: 3 },
  { name: 'Porcentagem', cat: 'porcentagem', n: 3 },
  { name: 'Geometria', cat: 'geometria', n: 3 },
  { name: 'Números e Operações', cat: 'numeros', n: 3 },
  { name: 'Álgebra', cat: 'algebra', n: 3 },
  { name: 'Medidas e Escalas', cat: 'medidas', n: 3 },
  { name: 'Probabilidade e Estatística', cat: 'probabilidade', n: 3 },
  { name: 'Desafio Mestre', cat: 'final', n: 3 },
];

export const CITY = {
  pavement: { z0: 26, z1: 35, x0: -14, x1: 14 },
  entranceZ: 25.2,
};

export const ARENA = {
  x0: -23, x1: -18, z0: -14, z1: -10,
  enter: { x: -20.5, z: -10 },
  npc: { x: -20.5, z: -11.6, c: '#F39C12', label: 'Árbitro da Arena' },
};

export const FARM_ZONE = {
  x0: -12, x1: 12, z0: -8, z1: 4,
  slots: [
    { id: 'slot_1', p: [-10, -8], rot: 0 },
    { id: 'slot_2', p: [10, -6], rot: 0 },
    { id: 'slot_3', p: [-10, -2], rot: 0 },
    { id: 'slot_4', p: [10, 2], rot: 0 },
  ],
};

export const BUILDING_3D = {
  celeiro: { w: 5, d: 4, h: 3, wall: '#A0522D', roof: '#7C3AED', door: '#6B4226' },
  estufa: { w: 4, d: 4, h: 3, wall: '#BFE8FF', roof: '#E8F6FF', door: '#9BD8F5', glass: true },
  moinho: { w: 3, d: 3, h: 5, wall: '#E0D5C5', roof: '#8E5B2F', door: '#6B4226' },
  granja: { w: 4, d: 3, h: 2, wall: '#D9B36A', roof: '#C94F1D', door: '#6B4226' },
  cocheira: { w: 5, d: 4, h: 3, wall: '#8B4513', roof: '#F5F5F5', door: '#6B4226' },
};

export const ANIMAL_DEFS = {
  vaca: { name: 'Vaca', emoji: '🐄', color: '#F5F5F5', spot: '#2B2B2B', w: 0.9, h: 0.7 },
  galinha: { name: 'Galinha', emoji: '🐔', color: '#FFFFFF', spot: '#E74C3C', w: 0.5, h: 0.5 },
  ovelha: { name: 'Ovelha', emoji: '🐑', color: '#F0EDE6', spot: '#9A9A9A', w: 0.8, h: 0.65 },
  porco: { name: 'Porco', emoji: '🐷', color: '#F5A3B8', spot: '#E07B9A', w: 0.75, h: 0.6 },
  cavalo: { name: 'Cavalo', emoji: '🐴', color: '#8B5A2B', spot: '#5C3D22', w: 1.1, h: 1.0 },
};

export const WILDLIFE_DEFS = {
  passaro: { name: 'Pássaro', emoji: '🐦', color: '#4FC3F7', w: 0.35 },
  coelho: { name: 'Coelho', emoji: '🐰', color: '#E8D5C2', w: 0.5 },
  esquilo: { name: 'Esquilo', emoji: '🐿️', color: '#C89B6E', w: 0.45 },
  borboleta: { name: 'Borboleta', emoji: '🦋', color: '#EC4899', w: 0.3 },
};

export const SHOP_SPOT = { x: 14, z: 6 };

export const LANDMARKS = [
  { label: 'Escola do Conhecimento', p: [0, -13], y: 6.8, c: '#5DADE2' },
  { label: 'Fazenda Matemática', p: [-12, 10], y: 5.5, c: '#27AE60' },
  { label: 'Praça Central', p: [0, -3], y: 4, c: '#F39C12' },
  { label: 'Biblioteca das Fórmulas', p: [0.5, 30], y: 8.6, c: '#8B4513' },
  { label: 'Estações do Saber', p: [0, 3], y: 4, c: '#7C3AED' },
];

export const NPC_DIALOGS = {
  IARA: 'Ariston, temos um problema. A ponte para a Cidade da Matemática está quebrada! Responda Desafios Matemáticos para ganhar materiais e reconstruí-la. Vamos lá?',
  Professor: 'A matemática é a ponte entre o problema e a solução. Ganhe materiais respondendo questões!',
  Agricultor: 'Plante, colha e troque pela economia da fazenda. Os recursos da ponte também vêm dos estudos!',
  Mercador: 'Encontre moedas pelo mundo e troque na loja. Boa exploração!',
  CityTeacher: 'Bem-vindo(a) à Cidade da Matemática! Aqui cada resposta abre novos caminhos.',
  ArenaReferee: 'A Arena do Conhecimento é um campeonato de raciocínio: Frações, Porcentagem, Geometria e um Desafio Mestre. Mostre seu poder!',
  Guardia: 'As Estações do Saber reúnem o conhecimento das 9 matérias da BNCC. Complete cada uma e brilhe!',
  Jardineira: 'Olha que mundo cheio de vida! Comprou animais na fazenda? Eles também aparecem aqui no mundo 3D. 🐄',
  Cartografo: 'Explore todos os cantos do mapa. Cada ponto de exploração vale ouro… literalmente! 💰',
  Musicista: 'A música é matemática em forma de som. Estude e sinta o ritmo! 🎵',
  Guia: 'Use as teclas WASD para andar, E para interagir e M para ver o mapa. O botão de ajuda ❓ mostra tudo!',
};

export const TUTORIAL_STEPS = [
  { title: 'Bem-vindo ao Mundo IARA!', body: 'Explore a Fazenda do Conhecimento em 3D. Este é o seu mundo de estudos e diversão.', icon: '🌍' },
  { title: 'Como andar', body: 'Use WASD (ou as setas) para andar, SHIFT para correr e ESPAÇO para pular. Arraste o mouse para girar a câmera.', icon: '🎮' },
  { title: 'Interaja com o mundo', body: 'Aproxime-se de personagens e estações e pressione E para conversar, aceitar desafios e comprar.', icon: '✋' },
  { title: 'Complete as Estações do Saber', body: 'São 9 estações, uma para cada matéria da BNCC. Ganhe Pontos de Exploração e a medalha Enciclopédico!', icon: '🧠' },
  { title: 'Sua fazenda no mundo', body: 'Animais e celeiros comprados na Fazendinha 2D aparecem aqui! Distribua sua vida pelo mundo.', icon: '🐄' },
  { title: 'Dica: o mapa', body: 'Pressione M para abrir o mapa. E o botão ❓ no topo traz este guia sempre que precisar.', icon: '🗺️' },
];

export const EXPLORATION_REDEEM_ITEMS = [
  { id: 'madeira_10', type: 'material', icon: '🪵', name: '+10 Madeira', points: 8, material: 'madeira', qty: 10 },
  { id: 'pedra_10', type: 'material', icon: '🪨', name: '+10 Pedra', points: 8, material: 'pedra', qty: 10 },
  { id: 'blocos_10', type: 'material', icon: '🧱', name: '+10 Blocos', points: 8, material: 'blocos', qty: 10 },
  { id: 'sementes_milho', type: 'seed', icon: '🌽', name: '10 Sementes de Milho', points: 12, seed: 'milho', qty: 10 },
  { id: 'sementes_cafe', type: 'seed', icon: '☕', name: '5 Sementes de Café', points: 15, seed: 'cafe', qty: 5 },
  { id: 'fogos', type: 'decor', icon: '🎆', name: 'Fogos de Artifício', points: 20, decor: 'fireworks' },
  { id: 'coroa', type: 'decor', icon: '👑', name: 'Coroa do Saber', points: 40, decor: 'crown' },
];

export function farmBuildingCells(farm) {
  const buildings = farm?.buildings || [];
  if (!buildings.length) return [];
  const cells = [];
  buildings.forEach((b, i) => {
    const spec = BUILDING_3D[b.id];
    const slot = FARM_ZONE.slots[i % FARM_ZONE.slots.length];
    if (!spec || !slot) return;
    const w = spec.w || 4;
    const d = spec.d || 4;
    const h = spec.h || 3;
    const x0 = Math.round(slot.p[0] - w / 2);
    const z0 = Math.round(slot.p[1] - d / 2);
    const cx = Math.round(slot.p[0]);
    for (let y = 1; y <= h; y++) {
      for (let x = x0; x < x0 + w; x++) {
        for (let z = z0; z < z0 + d; z++) {
          const edge = x === x0 || x === x0 + w - 1 || z === z0 || z === z0 + d - 1;
          if (!edge) continue;
          const isFront = z === z0;
          if (isFront && x === cx && y <= 2) continue;
          cells.push({ x, y, z, c: spec.wall });
        }
      }
    }
    for (let x = x0; x < x0 + w; x++) {
      for (let z = z0; z < z0 + d; z++) {
        cells.push({ x, y: h + 1, z, c: spec.roof });
      }
    }
    cells.push({ x: cx, y: 1, z: z0, c: spec.door });
  });
  return cells;
}