export const pagesConfig = {
  mainPage: "Home",
  Pages: {
    Home: null,
    Dashboard: null,
    Activities: null,
    PlayActivity: null,
    MyReport: null,
    Medals: null,
    Groups: null,
    ActivityManager: null,
    Attendance: null,
    Reports: null,
    Teachers: null,
    Classes: null,
    Users: null,
    Mural: null,
    CharacterCreation: null,
    GameMap: null,
    Farm: null,
    FarmShop: null,
    FarmMissions: null,
    FarmRanking: null,
    FarmAdmin: null,
    Curriculum: null,
    Profile: null,
    PainelUsuario: null,
    Acesso: null,
  }
};
